version: '2.2'
services:
  globehopper:
    build:
      context: ./
      dockerfile: Dockerfile
    image: globehopperspringdata
    ports:
      - 8085
    networks:
      - network1
    scale: 3

networks:
  network1: